In [3]:
pip install tensorflow

  Using cached tensorflow-2.21.0-cp312-cp312-win_amd64.whl.metadata (4.5 kB)
Using cached tensorflow-2.21.0-cp312-cp312-win_amd64.whl (350.9 MB)
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\Test\\Desktop\\DEPI-ONL4_AIS2_S2\\.env\\Lib\\site-packages\\tensorflow\\_api\\v2\\compat\\v2\\signal\\__init__.py'
Check the permissions.



In [4]:
import tensorflow as tf

  Using cached wheel-0.46.3-py3-none-any.whl.metadata (2.4 kB)
   ---------------------------------------- 0.0/350.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/350.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/350.9 MB 2.1 MB/s eta 0:02:48
   ---------------------------------------- 1.0/350.9 MB 1.9 MB/s eta 0:03:01
   ---------------------------------------- 1.0/350.9 MB 1.9 MB/s eta 0:03:01
   ---------------------------------------- 1.8/350.9 MB 1.9 MB/s eta 0:03:01
   ---------------------------------------- 1.8/350.9 MB 1.9 MB/s eta 0:03:01
   ---------------------------------------- 2.6/350.9 MB 1.9 MB/s eta 0:03:00
   ---------------------------------------- 2.9/350.9 MB 1.9 MB/s eta 0:03:03
   ---------------------------------------- 3.4/350.9 MB 1.9 MB/s eta 0:03:03
   ---------------------------------------- 3.7/350.9 MB 1.9 MB/s eta 0:03:02
   ---------------------------------------- 4.2/350.9 MB 1.9 MB/s eta 0:03:02
    -----------

In [5]:
x = tf.constant([[5,2],[1,3]]) # enter as a constant values
x   #in tensor format 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 2],
       [1, 3]], dtype=int32)>

In [6]:
tf.random.normal(shape=(2,2),mean=0.,stddev=1.)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.15433753, -0.8175336 ],
       [-0.5826782 , -1.0546175 ]], dtype=float32)>

In [7]:
init_val = tf.random.normal(shape=(2,2))
a = tf.Variable(init_val)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.4208719, -0.6470998],
       [-0.8632826, -1.6215948]], dtype=float32)>


In [8]:
a = tf.random.normal(shape=(2,2))
b = a = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
print(d)

tf.Tensor(
[[0.81297445 6.932706  ]
 [9.945556   7.168599  ]], shape=(2, 2), dtype=float32)


In [1]:
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv