# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [ ]:
import numpy as np

def array_factory(mode: str, shape, value=None):
    """
    Creates NumPy arrays based on the selected mode.

    :param mode: Type of array ('zeros', 'ones', 'full', 'identity')
    :mode type:str
    :param shape: Dimensions of the array 
    :shape type:(int for 1D or identity, tuple for multi-dimensional)
    :param value: Fill value when using 'full' (optional)
    :return: Generated NumPy array
    :rtype: numpy.ndarray
    """
    if mode == 'identity':      
        if type(shape) != int or shape < 0:   
            raise ValueError("shape must be a non-negative integer for 'identity'")
        return np.identity(shape)    
    
    if type(shape) != int and type(shape) != tuple:  
        raise ValueError("shape must be an integer or tuple of integers")
    
    if mode == 'zeros':       
        return np.zeros(shape)
    elif mode == 'ones':     
        return np.ones(shape)
    elif mode == 'full':     
        if value is None:    
            raise ValueError("value must be provided for 'full' mode")
        return np.full(shape, value) 
    else:       
        raise ValueError("Invalid mode. Choose from 'zeros', 'ones', 'full', 'identity'")

# Example usage:
print(array_factory('zeros', (2,3)))
print(array_factory('ones', (3,2)))
print(array_factory('full', (2,2), value=7))
print(array_factory('identity', 3))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [ ]:
import numpy as np

def secure_reshape_and_stack(data1:list, data2:list, new_shape:tuple):
    """
    Converts two datasets to NumPy arrays, reshapes the first dataset,
    and vertically stacks them into a single matrix.

    :param data1: The first dataset to be reshaped
    :data1 type: array-like
    :param data2: The second dataset to be stacked below the first dataset
    :data2 type: array-like
    :param new_shape: The desired shape for the first dataset after reshaping
    :new_shape type: tuple
    :return: Combined matrix after reshaping and stacking
    :rtype: numpy.ndarray
    """
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape)
        num_cols = reshaped_arr1.shape[1]

        if arr2.ndim == 1:
            if arr2.size % num_cols != 0:
                raise ValueError(
                    f"Cannot reshape data2 with {arr2.size} elements into a matrix with {num_cols} columns"
                )
            arr2 = arr2.reshape(-1, num_cols)
        elif arr2.ndim == 2:
            if arr2.shape[1] != num_cols:
                raise ValueError(
                    f"data2 has {arr2.shape[1]} columns but should have {num_cols} to match data1"
                )
        else:
            raise ValueError("data2 must be 1D or 2D")

        combined_dataset = np.vstack([reshaped_arr1, arr2])
        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

# Example usage:
data1 = [1,2,3,4,5,6]
data2 = [7,8,9,10,11,12,13,14,15,16,17,18]
print(secure_reshape_and_stack(data1, data2, (2,3)))



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [8]:
import numpy as np

def apply_threshold(arr: list, threshold: int, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) and replaces them with a new value.

    :param arr: Input array-like data
    :arr type: list
    :param threshold: Threshold value for comparison
    :threshold type: int
    :param replacement_value: Value to replace elements that meet the condition
    :replacement_value type: int
    :return: Modified array with elements replaced based on the condition
    :return type: numpy.ndarray
    """
    arr = np.array(arr)
    condition = arr >= threshold
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr
#Example usage:
data = [1, 5, 7, 2]
print(apply_threshold(data, 5))


[ 1 -1 -1  2]


TestCase

In [9]:
import numpy as np

branch_a = [1, 2, 3, 4, 5, 6]
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape branch_a to 2x3
reshaped_a = np.array(branch_a).reshape((2, 3))
# Convert branch_b to np.array (already 2x3)
arr_b = np.array(branch_b)

# Vertically stack
final_report = np.vstack([reshaped_a, arr_b])
print(final_report)
print(final_report.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [10]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])