In [1]:
import numpy as np

def set_matrix_zeros(matrix):
    """
    Modifies an m x n matrix in-place. If an element is 0, its entire 
    row and column are set to 0.
    
    Strategy: 
    1. Identify all row and column indices that contain at least one zero.
    2. Use NumPy slicing to efficiently wipe those rows and columns.
    """
    # Track unique indices of rows and columns that need to be zeroed
    rows_to_zero = set()
    cols_to_zero = set()
    
    m = len(matrix)
    n = len(matrix[0]) if m > 0 else 0
    
    # Phase 1: Scan the matrix to locate zeros
    for i in range(m):
        for j in range(n):
            if matrix[i][j] == 0:
                rows_to_zero.add(i)
                cols_to_zero.add(j)
    
    # Phase 2: Apply changes using NumPy's optimized broadcasting/slicing
    for r in rows_to_zero:
        matrix[r, :] = 0  # Set the entire row at index 'r' to zero
    
    for c in cols_to_zero:
        matrix[:, c] = 0  # Set the entire column at index 'c' to zero
    
    return matrix

# Example Usage:
mat = np.array([
    [1, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

# Note: Ensure the function name called matches the definition
set_matrix_zeros(mat)
print(mat)

[[1 0 1]
 [0 0 0]
 [1 0 1]]
